all: ../inc/dance.h ../src/dance.c ../src/generate.c
	gcc -O3 -g -Wall -Wextra -Wpedantic -I../inc -o generate ../src/dance.c ../src/generate.c

gen2: ../inc/dance.h ../src/dance.c ../src/generateDist.c
	gcc -O3 -g -Wall -Wextra -Wpedantic -I../inc -o generate2 ../src/dance.c ../src/generateDist.c
